### ISSUE TITLE
AttributeError: 'VehicleStatus' object has no attribute 'ARMING_STATE_DISARMED'

### ISSUE THREAD

**Issue by Adeljc8** [Jaeyoung-Lim/px4-offboard#27]
Hello, 
Why am I getting this attribute error:
**self.arming_state = vehicle_status.ARMING_STATE_DISARMED
AttributeError: 'VehicleStatus' object has no attribute 'ARMING_STATE_DISARMED'**

Thank you in advance.

**Comment by Jaeyoung-Lim** [comment]
@Adeljc8 That is strange, since it exists: https://github.com/PX4/px4_msgs/blob/bd9dc0fae0162960a31af8f232a9e9f85522ae73/msg/VehicleStatus.msg#L9

**Comment by ciresimo** [comment]
Hey @Jaeyoung-Lim 
I tried to launch you example and got the same error
I'm using PX4 main, should I revert to an older version?

**Comment by Jaeyoung-Lim** [comment]
@ciresimo This is not really related to the px4 version, but rather the px4_msgs you are using.(Which needs to be compatible with px4)

 Could you check if the message field exists in the version you are using?

**Comment by ciresimo** [comment]
Ok solved it
As suggested in px4_msgs repo I checked out to release/1.14 since I was using px4 1.14.3
It was my fault  since I did not look at the readme
I tried an it works fine also on main (both px4 and px4_msgs) so probably yesterday I did not fetch/pull something
Thanks for the suggestion and for this cool example

**Comment by Jaeyoung-Lim** [comment]
@ciresimo Thanks for the update!
